
package webservice;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "SessionEJB1Bean", targetNamespace = "http://webservice/")
@XmlSeeAlso({ ObjectFactory.class })
public interface SessionEJB1Bean {


    /**
     *
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "commit", targetNamespace = "http://webservice/", className = "webservice.Commit")
    @ResponseWrapper(localName = "commitResponse", targetNamespace = "http://webservice/",
                     className = "webservice.CommitResponse")
    @Action(input = "http://webservice/SessionEJB1Bean/commitRequest",
            output = "http://webservice/SessionEJB1Bean/commitResponse")
    public boolean commit(@WebParam(name = "arg0", targetNamespace = "") int arg0);

    /**
     *
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setSessionContext", targetNamespace = "http://webservice/",
                    className = "webservice.SetSessionContext")
    @ResponseWrapper(localName = "setSessionContextResponse", targetNamespace = "http://webservice/",
                     className = "webservice.SetSessionContextResponse")
    @Action(input = "http://webservice/SessionEJB1Bean/setSessionContextRequest",
            output = "http://webservice/SessionEJB1Bean/setSessionContextResponse")
    public void setSessionContext(@WebParam(name = "arg0", targetNamespace = "") Object arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "borraSolicitud", targetNamespace = "http://webservice/",
                    className = "webservice.BorraSolicitud")
    @ResponseWrapper(localName = "borraSolicitudResponse", targetNamespace = "http://webservice/",
                     className = "webservice.BorraSolicitudResponse")
    @Action(input = "http://webservice/SessionEJB1Bean/borraSolicitudRequest",
            output = "http://webservice/SessionEJB1Bean/borraSolicitudResponse")
    public String borraSolicitud(@WebParam(name = "arg0", targetNamespace = "") Solicitudro1 arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertaSolicitud", targetNamespace = "http://webservice/",
                    className = "webservice.InsertaSolicitud")
    @ResponseWrapper(localName = "insertaSolicitudResponse", targetNamespace = "http://webservice/",
                     className = "webservice.InsertaSolicitudResponse")
    @Action(input = "http://webservice/SessionEJB1Bean/insertaSolicitudRequest",
            output = "http://webservice/SessionEJB1Bean/insertaSolicitudResponse")
    public String insertaSolicitud(@WebParam(name = "arg0", targetNamespace = "") Solicitudro1 arg0);

    /**
     *
     * @return
     *     returns java.util.List<webservice.Solicitudro1>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSolicitudes", targetNamespace = "http://webservice/",
                    className = "webservice.GetSolicitudes")
    @ResponseWrapper(localName = "getSolicitudesResponse", targetNamespace = "http://webservice/",
                     className = "webservice.GetSolicitudesResponse")
    @Action(input = "http://webservice/SessionEJB1Bean/getSolicitudesRequest",
            output = "http://webservice/SessionEJB1Bean/getSolicitudesResponse")
    public List<Solicitudro1> getSolicitudes();

    /**
     *
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "closeConexion", targetNamespace = "http://webservice/",
                    className = "webservice.CloseConexion")
    @ResponseWrapper(localName = "closeConexionResponse", targetNamespace = "http://webservice/",
                     className = "webservice.CloseConexionResponse")
    @Action(input = "http://webservice/SessionEJB1Bean/closeConexionRequest",
            output = "http://webservice/SessionEJB1Bean/closeConexionResponse")
    public boolean closeConexion(@WebParam(name = "arg0", targetNamespace = "") int arg0);

    /**
     *
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getConection", targetNamespace = "http://webservice/",
                    className = "webservice.GetConection")
    @ResponseWrapper(localName = "getConectionResponse", targetNamespace = "http://webservice/",
                     className = "webservice.GetConectionResponse")
    @Action(input = "http://webservice/SessionEJB1Bean/getConectionRequest",
            output = "http://webservice/SessionEJB1Bean/getConectionResponse")
    public int getConection();

    /**
     *
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizaSolicitud", targetNamespace = "http://webservice/",
                    className = "webservice.ActualizaSolicitud")
    @ResponseWrapper(localName = "actualizaSolicitudResponse", targetNamespace = "http://webservice/",
                     className = "webservice.ActualizaSolicitudResponse")
    @Action(input = "http://webservice/SessionEJB1Bean/actualizaSolicitudRequest",
            output = "http://webservice/SessionEJB1Bean/actualizaSolicitudResponse")
    public String actualizaSolicitud(@WebParam(name = "arg0", targetNamespace = "") Solicitudro1 arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns java.util.List<webservice.LineaSolicitud>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLineaSolicitudes", targetNamespace = "http://webservice/",
                    className = "webservice.GetLineaSolicitudes")
    @ResponseWrapper(localName = "getLineaSolicitudesResponse", targetNamespace = "http://webservice/",
                     className = "webservice.GetLineaSolicitudesResponse")
    @Action(input = "http://webservice/SessionEJB1Bean/getLineaSolicitudesRequest",
            output = "http://webservice/SessionEJB1Bean/getLineaSolicitudesResponse")
    public List<LineaSolicitud> getLineaSolicitudes(@WebParam(name = "arg0", targetNamespace = "") Long arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertaLineasSolicitud", targetNamespace = "http://webservice/",
                    className = "webservice.InsertaLineasSolicitud")
    @ResponseWrapper(localName = "insertaLineasSolicitudResponse", targetNamespace = "http://webservice/",
                     className = "webservice.InsertaLineasSolicitudResponse")
    @Action(input = "http://webservice/SessionEJB1Bean/insertaLineasSolicitudRequest",
            output = "http://webservice/SessionEJB1Bean/insertaLineasSolicitudResponse")
    public String insertaLineasSolicitud(@WebParam(name = "arg0", targetNamespace = "") LineaSolicitud arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizaLineasSolicitud", targetNamespace = "http://webservice/",
                    className = "webservice.ActualizaLineasSolicitud")
    @ResponseWrapper(localName = "actualizaLineasSolicitudResponse", targetNamespace = "http://webservice/",
                     className = "webservice.ActualizaLineasSolicitudResponse")
    @Action(input = "http://webservice/SessionEJB1Bean/actualizaLineasSolicitudRequest",
            output = "http://webservice/SessionEJB1Bean/actualizaLineasSolicitudResponse")
    public String actualizaLineasSolicitud(@WebParam(name = "arg0", targetNamespace = "") LineaSolicitud arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "borraLineasSolicitud", targetNamespace = "http://webservice/",
                    className = "webservice.BorraLineasSolicitud")
    @ResponseWrapper(localName = "borraLineasSolicitudResponse", targetNamespace = "http://webservice/",
                     className = "webservice.BorraLineasSolicitudResponse")
    @Action(input = "http://webservice/SessionEJB1Bean/borraLineasSolicitudRequest",
            output = "http://webservice/SessionEJB1Bean/borraLineasSolicitudResponse")
    public String borraLineasSolicitud(@WebParam(name = "arg0", targetNamespace = "") LineaSolicitud arg0);

    /**
     *
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaTodasLasLineas", targetNamespace = "http://webservice/",
                    className = "webservice.ConsultaTodasLasLineas")
    @ResponseWrapper(localName = "consultaTodasLasLineasResponse", targetNamespace = "http://webservice/",
                     className = "webservice.ConsultaTodasLasLineasResponse")
    @Action(input = "http://webservice/SessionEJB1Bean/consultaTodasLasLineasRequest",
            output = "http://webservice/SessionEJB1Bean/consultaTodasLasLineasResponse")
    public int consultaTodasLasLineas();

}
