
package webservice;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "SessionEJB1Bean", targetNamespace = "http://webservice/")
@XmlSeeAlso({ ObjectFactory.class })
public interface SessionEJB1Bean {


    /**
     *
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "closeConexion", targetNamespace = "http://webservice/",
                    className = "webservice.CloseConexion")
    @ResponseWrapper(localName = "closeConexionResponse", targetNamespace = "http://webservice/",
                     className = "webservice.CloseConexionResponse")
    @Action(input = "http://webservice/SessionEJB1Bean/closeConexionRequest",
            output = "http://webservice/SessionEJB1Bean/closeConexionResponse")
    public boolean closeConexion(@WebParam(name = "arg0", targetNamespace = "") int arg0);

    /**
     *
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getConection", targetNamespace = "http://webservice/",
                    className = "webservice.GetConection")
    @ResponseWrapper(localName = "getConectionResponse", targetNamespace = "http://webservice/",
                     className = "webservice.GetConectionResponse")
    @Action(input = "http://webservice/SessionEJB1Bean/getConectionRequest",
            output = "http://webservice/SessionEJB1Bean/getConectionResponse")
    public int getConection();

    /**
     *
     * @return
     *     returns java.util.List<webservice.Solicitudro1>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSolicitudes", targetNamespace = "http://webservice/",
                    className = "webservice.GetSolicitudes")
    @ResponseWrapper(localName = "getSolicitudesResponse", targetNamespace = "http://webservice/",
                     className = "webservice.GetSolicitudesResponse")
    @Action(input = "http://webservice/SessionEJB1Bean/getSolicitudesRequest",
            output = "http://webservice/SessionEJB1Bean/getSolicitudesResponse")
    public List<Solicitudro1> getSolicitudes();

    /**
     *
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertaSolicitud", targetNamespace = "http://webservice/",
                    className = "webservice.InsertaSolicitud")
    @ResponseWrapper(localName = "insertaSolicitudResponse", targetNamespace = "http://webservice/",
                     className = "webservice.InsertaSolicitudResponse")
    @Action(input = "http://webservice/SessionEJB1Bean/insertaSolicitudRequest",
            output = "http://webservice/SessionEJB1Bean/insertaSolicitudResponse")
    public boolean insertaSolicitud(@WebParam(name = "arg0", targetNamespace = "") Solicitudro1 arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "borraSolicitud", targetNamespace = "http://webservice/",
                    className = "webservice.BorraSolicitud")
    @ResponseWrapper(localName = "borraSolicitudResponse", targetNamespace = "http://webservice/",
                     className = "webservice.BorraSolicitudResponse")
    @Action(input = "http://webservice/SessionEJB1Bean/borraSolicitudRequest",
            output = "http://webservice/SessionEJB1Bean/borraSolicitudResponse")
    public boolean borraSolicitud(@WebParam(name = "arg0", targetNamespace = "") Solicitudro1 arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizaSolicitud", targetNamespace = "http://webservice/",
                    className = "webservice.ActualizaSolicitud")
    @ResponseWrapper(localName = "actualizaSolicitudResponse", targetNamespace = "http://webservice/",
                     className = "webservice.ActualizaSolicitudResponse")
    @Action(input = "http://webservice/SessionEJB1Bean/actualizaSolicitudRequest",
            output = "http://webservice/SessionEJB1Bean/actualizaSolicitudResponse")
    public boolean actualizaSolicitud(@WebParam(name = "arg0", targetNamespace = "") Solicitudro1 arg0);

    /**
     *
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setSessionContext", targetNamespace = "http://webservice/",
                    className = "webservice.SetSessionContext")
    @ResponseWrapper(localName = "setSessionContextResponse", targetNamespace = "http://webservice/",
                     className = "webservice.SetSessionContextResponse")
    @Action(input = "http://webservice/SessionEJB1Bean/setSessionContextRequest",
            output = "http://webservice/SessionEJB1Bean/setSessionContextResponse")
    public void setSessionContext(@WebParam(name = "arg0", targetNamespace = "") Object arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "commit", targetNamespace = "http://webservice/", className = "webservice.Commit")
    @ResponseWrapper(localName = "commitResponse", targetNamespace = "http://webservice/",
                     className = "webservice.CommitResponse")
    @Action(input = "http://webservice/SessionEJB1Bean/commitRequest",
            output = "http://webservice/SessionEJB1Bean/commitResponse")
    public boolean commit(@WebParam(name = "arg0", targetNamespace = "") int arg0);

}
