package webservice;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.2.0.1224
import java.util.Collection;
import webservice.Solicitudro1;

public class SessionEJB1BeanPortClient {
    public static void main(String[] args) {
        SessionEJB1BeanService sessionEJB1BeanService = new SessionEJB1BeanService();
        SessionEJB1Bean sessionEJB1Bean = sessionEJB1BeanService.getSessionEJB1BeanPort();
        int i = sessionEJB1Bean.getConection();
        System.out.println(i);
        Collection<Solicitudro1> sol =  sessionEJB1Bean.getSolicitudes();
        sessionEJB1Bean.closeConexion(i);
    }
}
