package Vistas;

/**
 *
 * @author jose pablo
 */
public class crearPedido extends javax.swing.JFrame {


                    public crearPedido() {
                           initComponents();
                       }

                       /**
                        * This method is called from within the constructor to initialize the form.
                        * WARNING: Do NOT modify this code. The content of this method is always
                        * regenerated by the Form Editor.
                        */
                       @SuppressWarnings("unchecked")
                       // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
                       private void initComponents() {

                           crearPedidoBT = new javax.swing.JButton();
                           listaLineas = new java.awt.List();
                           anadeLineaBT = new javax.swing.JButton();
                           cantidadSN = new javax.swing.JSpinner();
                           jLabel1 = new javax.swing.JLabel();
                           jLabel2 = new javax.swing.JLabel();
                           jLabel3 = new javax.swing.JLabel();
                           borrarLineaBT = new javax.swing.JButton();
                           idPedido = new javax.swing.JSpinner();
                           jLabel4 = new javax.swing.JLabel();
                           fchMaximaTX = new javax.swing.JTextField();
                           fchPedidoTX = new javax.swing.JTextField();
                           jLabel5 = new javax.swing.JLabel();
                           jLabel6 = new javax.swing.JLabel();
                           jLabel7 = new javax.swing.JLabel();
                           clienteID = new javax.swing.JSpinner();
                           prendaID = new javax.swing.JSpinner();
                           tallaID = new javax.swing.JSpinner();
                           jLabel8 = new javax.swing.JLabel();
                           ordenID = new javax.swing.JSpinner();

                           setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                           crearPedidoBT.setText("Crear pedido");

                           anadeLineaBT.setText("Agregar linea");

                           jLabel1.setText("Cantidad");

                           jLabel2.setText("Talla");

                           jLabel3.setText("Prenda");

                           borrarLineaBT.setText("Borrar linea");

                           jLabel4.setText("ID Pedido");

                           fchMaximaTX.setText("fch");

                           fchPedidoTX.setText("fch");

                           jLabel5.setText("Facha maxima");

                           jLabel6.setText("Fecha pedido");

                           jLabel7.setText("ID Cliente");

                           jLabel8.setText("ID Orden");

                           javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                           getContentPane().setLayout(layout);
                           layout.setHorizontalGroup(
                               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                   .addContainerGap()
                                   .addComponent(listaLineas, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                           .addComponent(borrarLineaBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                           .addComponent(anadeLineaBT, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                           .addGroup(layout.createSequentialGroup()
                                               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                   .addComponent(cantidadSN)
                                                   .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                                   .addComponent(jLabel2)
                                                   .addComponent(jLabel3))
                                               .addGap(15, 15, 15)))
                                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                           .addComponent(prendaID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                           .addComponent(tallaID, javax.swing.GroupLayout.Alignment.LEADING))
                                       .addComponent(jLabel7)
                                       .addComponent(clienteID, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                       .addComponent(jLabel8)
                                       .addComponent(crearPedidoBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                       .addComponent(idPedido)
                                       .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                       .addComponent(jLabel5)
                                       .addComponent(jLabel6)
                                       .addComponent(fchMaximaTX)
                                       .addComponent(fchPedidoTX)
                                       .addComponent(ordenID))
                                   .addContainerGap())
                           );
                           layout.setVerticalGroup(
                               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                               .addGroup(layout.createSequentialGroup()
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGroup(layout.createSequentialGroup()
                                           .addContainerGap(167, Short.MAX_VALUE)
                                           .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                               .addComponent(jLabel7)
                                               .addComponent(jLabel8))
                                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                           .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                               .addComponent(clienteID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                               .addComponent(ordenID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                           .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                               .addComponent(jLabel3)
                                               .addComponent(jLabel4))
                                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                           .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                               .addComponent(idPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                               .addComponent(prendaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                           .addGap(18, 18, 18)
                                           .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                               .addComponent(jLabel2)
                                               .addComponent(jLabel5))
                                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                           .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                               .addComponent(fchMaximaTX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                               .addComponent(tallaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                           .addGap(18, 18, 18)
                                           .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                               .addComponent(jLabel1)
                                               .addComponent(jLabel6))
                                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                           .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                               .addComponent(cantidadSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                               .addComponent(fchPedidoTX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                           .addGap(18, 18, 18)
                                           .addComponent(anadeLineaBT)
                                           .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                               .addGroup(layout.createSequentialGroup()
                                                   .addGap(22, 22, 22)
                                                   .addComponent(crearPedidoBT))
                                               .addGroup(layout.createSequentialGroup()
                                                   .addGap(18, 18, 18)
                                                   .addComponent(borrarLineaBT))))
                                       .addComponent(listaLineas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                   .addContainerGap())
                           );

                           pack();
                       }// </editor-fold>                        


                       // Variables declaration - do not modify                     
                       public javax.swing.JButton anadeLineaBT;
                       public javax.swing.JButton borrarLineaBT;
                       public javax.swing.JSpinner cantidadSN;
                       public javax.swing.JSpinner clienteID;
                       public javax.swing.JButton crearPedidoBT;
                       public javax.swing.JTextField fchMaximaTX;
                       public javax.swing.JTextField fchPedidoTX;
                       public javax.swing.JSpinner idPedido;
                       private javax.swing.JLabel jLabel1;
                       private javax.swing.JLabel jLabel2;
                       private javax.swing.JLabel jLabel3;
                       private javax.swing.JLabel jLabel4;
                       private javax.swing.JLabel jLabel5;
                       private javax.swing.JLabel jLabel6;
                       private javax.swing.JLabel jLabel7;
                       private javax.swing.JLabel jLabel8;
                       public java.awt.List listaLineas;
                       public javax.swing.JSpinner ordenID;
                       public javax.swing.JSpinner prendaID;
                       public javax.swing.JSpinner tallaID;
                       // End of variables declaration                   
                    }


